### ISSUE TITLE
Fix footer on facilities.html 

### ISSUE THREAD

**Issue by iwanikhalid** [nabelk/public_html#1]
![image](https://user-images.githubusercontent.com/751716/181475565-0e9c2167-2f78-4e7b-b1d6-6f361a042e44.png)

Need to move the content in red box to the 3rd column of footer

**Comment by nabelk** [comment]
**Commit Changes**
 https://github.com/nabelk/public_html/commit/26f97ec1a76b74d6ea689ebd6bd10edd8e2acbc2
